# Generated by Django 4.0.4 on 2022-06-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsao',
            name='Y_prev',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='previsao',
            name='Y_real',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
