# Generated by Django 4.0.4 on 2022-06-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_previsao_y_prev_alter_previsao_y_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsao',
            name='Y_prev',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='previsao',
            name='Y_real',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
