# Generated by Django 4.0.4 on 2022-06-24 14:53

from django.db import migrations
from RegHelper import carregar_dados
def load_data(apps,schema_editor):
    dm_model=apps.get_model('homepage','DadosModelo')
    X_ig,y_ig=carregar_dados()
    for x,y in zip(X_ig,y_ig):
        dm_model.objects.create(X=x,Y=y)
class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_previsao_y_prev_alter_previsao_y_real'),
    ]

    operations = [ migrations.RunPython(load_data)
    ]
